/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.tika.metadata.filter;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.function.UnaryOperator;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.tika.annotation.TikaComponent;
import org.apache.tika.metadata.Metadata;
import org.apache.tika.metadata.TikaCoreProperties;

/**
 * Rewrites 4.x metadata keys back to their 3.x spellings (or vice versa) so consumers pinned to 3.x
 * key names keep working after the 4.0 rename break. Opt-in; enable it in the metadata-filter chain
 * and it rewrites at the emit edge. Because it runs inside the {@link MetadataFilter} trusted bracket,
 * it may write reserved (e.g. {@code X-TIKA:}/{@code tk:}) keys that a plain String write couldn't.
 *
 * <p><b>Data-driven, not hand-coded.</b> The renames come from the committed migration table
 * (generated by joining the 3.x and 4.x field-attributed key tables — TIKA-4797). Three tiers:
 * <ul>
 *   <li><b>flat renames</b> — the enumerated key-for-key changes (the bulk);</li>
 *   <li><b>drops</b> — 3.x keys 4.x no longer emits (only relevant on ingest);</li>
 *   <li><b>prefix rules</b> — the open families whose suffix also transforms or is unbounded, so no
 *       flat table row can enumerate them: {@code tk:exception:}/{@code tk:warn:} snake&harr;kebab,
 *       {@code tk:digest:} algorithm names, and (TIKA-4816 stage 5a) the {@code KeyPrefix} renames
 *       {@code NER_}&harr;{@code ner:}, {@code grobid:header_}&harr;{@code grobid:header:},
 *       {@code envi.}&harr;{@code envi:}, and (post stage-5a, same rename batch)
 *       {@code streams-}&harr;{@code ogg:streams-} and the ISO19139 {@code Keywords }/
 *       {@code KeywordsType }/{@code ThesaurusNameTitle }/{@code ThesaurusNameAlternativeTitle }
 *       space-delimited 3.x families &harr; their {@code iso19115:keywords:}/
 *       {@code iso19115:keywords-type:}/{@code iso19115:thesaurus-name-title:}/
 *       {@code iso19115:thesaurus-name-alternative-title:} {@code KeyPrefix} spellings (one hop
 *       straight from the 3.x spelling, TIKA-4816 rename batch) —
 *       these are open vocabularies (entity types, TEI field names, ENVI header fields, stream
 *       kinds, indexed keyword groups), so the field-identity join that builds the flat table can
 *       never see them (it only ever sees {@code Property} fields, and these are {@code KeyPrefix}
 *       declarations with no enumerable suffix set); the suffix is carried through verbatim. One
 *       family isn't verbatim-suffix: GeoParser's alternate-location fields also lower-cased the
 *       field word ({@code Optional_NAME1}&harr;{@code geotopic:alt-name1}), so it gets its own
 *       small lookup ({@link #geotopicAlternateLocationRule}) instead of {@link #prefixSwapRule}.</li>
 * </ul>
 * Unmapped keys pass through unchanged (this is a compatibility bridge, not an allow-list).
 *
 * <p><b>Skeleton status (TIKA-4799):</b> the flat/drop/passthrough mechanism is complete; the
 * bundled table and the concrete prefix rules land with the rename PRs (the table resource is absent
 * until then, so the default filter is a safe no-op). See {@link #prefixRules} for where the
 * digest/exception rules slot in.
 */
@TikaComponent
public class LegacyKeyMigrationFilter extends MetadataFilterBase {

    /** V4_TO_V3 = egress (4.x output rewritten to 3.x keys, the BWC case); V3_TO_V4 = ingest. */
    public enum Direction { V4_TO_V3, V3_TO_V4 }

    /** Generated by the TIKA-4797 migration join; deposited into tika-core resources when renames land. */
    static final String DEFAULT_TABLE = "/org/apache/tika/metadata/metadata-migration-3x-4x.json";

    // {"v3":"...","v4":"..."} ; v4 == "DROPPED" marks a 3.x key with no 4.x successor.
    private static final Pattern ROW =
            Pattern.compile("\\{\"v3\":\"(.*?)\",\"v4\":\"(.*?)\"}");

    // 4.x digest keys use the JCA name (DigestDef.getJavaName); 3.x used the enum name. MD2/MD5 match.
    private static final Map<String, String> DIGEST_ALG_V4_TO_V3 = Map.of(
            "SHA-1", "SHA1", "SHA-256", "SHA256", "SHA-384", "SHA384", "SHA-512", "SHA512",
            "SHA3-256", "SHA3_256", "SHA3-384", "SHA3_384", "SHA3-512", "SHA3_512");
    private static final String V4_DIGEST = TikaCoreProperties.TIKA_META_PREFIX + "digest:";
    private static final String V3_DIGEST = TikaCoreProperties.LEGACY_TIKA_META_PREFIX + "digest:";

    public static class Config {
        public Direction direction = Direction.V4_TO_V3;
        public String table = DEFAULT_TABLE;
    }

    private final Map<String, String> renames;   // source key -> target key (direction applied)
    private final Set<String> drops;             // source keys to remove (ingest only)
    private final List<UnaryOperator<String>> prefixRules;

    public LegacyKeyMigrationFilter() {
        this(new Config());
    }

    public LegacyKeyMigrationFilter(Config config) {
        this(loadTable(config.table), config.direction);
    }

    /** Test/explicit hook. {@code table} is v3-&gt;v4 (with {@code null}/"DROPPED" = dropped). */
    LegacyKeyMigrationFilter(Map<String, String> table, Direction direction) {
        this.renames = new HashMap<>();
        this.drops = new HashSet<>();
        for (Map.Entry<String, String> e : table.entrySet()) {
            String v3 = e.getKey();
            String v4 = e.getValue();
            boolean dropped = v4 == null || "DROPPED".equals(v4);
            if (direction == Direction.V4_TO_V3) {
                if (!dropped) {
                    renames.put(v4, v3);       // 4.x key -> 3.x key
                }
            } else {                            // V3_TO_V4
                if (dropped) {
                    drops.add(v3);
                } else {
                    renames.put(v3, v4);
                }
            }
        }
        // Digest keys and the stage-5a KeyPrefix renames have no declaring Property field (digests
        // are synthesized; the others are open-vocabulary KeyPrefix families), so none of them are
        // in the flat table -- rewrite them by prefix rule instead. (Exception/warn keys ARE
        // enumerated in the table: they're Property fields, not open KeyPrefix vocabularies.)
        this.prefixRules = new ArrayList<>();
        this.prefixRules.add(digestRule(direction));
        this.prefixRules.add(prefixSwapRule(direction, "ner:", "NER_"));
        this.prefixRules.add(prefixSwapRule(direction, "grobid:header:", "grobid:header_"));
        this.prefixRules.add(prefixSwapRule(direction, "envi:", "envi."));
        // TIKA-4816 rename batch (post stage-5a): more open-vocabulary KeyPrefix families, same
        // shape as the three above -- verbatim suffix, prefix only.
        this.prefixRules.add(prefixSwapRule(direction, "ogg:streams-", "streams-"));
        // TIKA-4816 rename batch: v4Prefix is the FINAL 4.x spelling (iso19115:*), v3Prefix is
        // unchanged from the original 3.x spelling -- one hop, not a chain through the
        // intermediate "Keywords:"-shaped spelling these families used before this batch.
        this.prefixRules.add(prefixSwapRule(direction, "iso19115:keywords:", "Keywords "));
        this.prefixRules.add(prefixSwapRule(direction, "iso19115:keywords-type:", "KeywordsType "));
        this.prefixRules.add(
                prefixSwapRule(direction, "iso19115:thesaurus-name-title:", "ThesaurusNameTitle "));
        this.prefixRules.add(prefixSwapRule(direction, "iso19115:thesaurus-name-alternative-title:",
                "ThesaurusNameAlternativeTitle "));
        // GeoParser's alternate-location family isn't a verbatim-suffix swap: the old shape
        // upper-cased the field word and had no "alt-" marker ("Optional_NAME1"), the new shape
        // lower-cases it under a KeyPrefix ("geotopic:alt-name1") -- see geotopicAlternateLocationRule.
        this.prefixRules.add(geotopicAlternateLocationRule(direction));
    }

    @Override
    protected void filter(Metadata metadata) {
        for (String name : metadata.names()) {          // names() returns a snapshot copy
            if (drops.contains(name)) {
                metadata.remove(name);
                continue;
            }
            String mapped = renames.get(name);
            if (mapped == null) {
                for (UnaryOperator<String> rule : prefixRules) {
                    String r = rule.apply(name);
                    if (r != null) {
                        mapped = r;
                        break;
                    }
                }
            }
            if (mapped != null && !mapped.equals(name)) {
                String[] values = metadata.getValues(name);
                metadata.remove(name);
                for (String v : values) {
                    metadata.addTrusted(mapped, v);     // targets may be reserved (tk:/X-TIKA:)
                }
            }
            // unmapped -> pass through unchanged
        }
    }

    private static Map<String, String> loadTable(String resource) {
        Map<String, String> table = new HashMap<>();
        try (InputStream in = LegacyKeyMigrationFilter.class.getResourceAsStream(resource)) {
            if (in == null) {
                return table;   // not bundled yet -> no-op bridge
            }
            Matcher m = ROW.matcher(new String(in.readAllBytes(), StandardCharsets.UTF_8));
            while (m.find()) {
                table.put(unescape(m.group(1)), unescape(m.group(2)));
            }
        } catch (Exception e) {
            throw new IllegalStateException("could not read migration table " + resource, e);
        }
        return table;
    }

    private static String unescape(String s) {
        return s.replace("\\\"", "\"").replace("\\\\", "\\");
    }

    /**
     * A {@code KeyPrefix} rename (TIKA-4816 stage 5a): swaps a fixed prefix, carrying the
     * (unbounded, document/tool-derived) suffix through unchanged -- {@code v4Prefix + suffix}
     * &harr; {@code v3Prefix + suffix}.
     */
    private static UnaryOperator<String> prefixSwapRule(Direction direction, String v4Prefix,
            String v3Prefix) {
        boolean egress = direction == Direction.V4_TO_V3;
        String fromPrefix = egress ? v4Prefix : v3Prefix;
        String toPrefix = egress ? v3Prefix : v4Prefix;
        return name -> name.startsWith(fromPrefix) ? toPrefix + name.substring(fromPrefix.length()) : null;
    }

    // GeoParser's alternate-location word vocabulary is bounded (3 words) even though the trailing
    // index is not -- v4Word is what geotopic:alt- is followed by, v3Word is the pre-rename
    // upper-cased suffix word ("Optional_" + v3Word + index).
    private static final Map<String, String> GEOTOPIC_ALT_WORDS_V4_TO_V3 =
            Map.of("name", "NAME", "longitude", "LONGITUDE", "latitude", "LATITUDE");
    private static final Pattern GEOTOPIC_ALT_V4 =
            Pattern.compile("^geotopic:alt-(name|longitude|latitude)(\\d+)$");
    private static final Pattern GEOTOPIC_ALT_V3 =
            Pattern.compile("^Optional_(NAME|LONGITUDE|LATITUDE)(\\d+)$");

    /**
     * {@code geotopic:alt-<word><n>} &harr; {@code Optional_<WORD><n>} (GeoParser's
     * alternate-location fields, TIKA-4816). Not a verbatim-suffix {@link #prefixSwapRule}: the
     * rename also lower-cased the field word and inserted a delimiter ("Optional_NAME1" -&gt;
     * "geotopic:alt-name1"), so the word itself needs a (bounded, 3-entry) lookup; only the
     * trailing index is unbounded and carried through verbatim.
     */
    private static UnaryOperator<String> geotopicAlternateLocationRule(Direction direction) {
        boolean egress = direction == Direction.V4_TO_V3;
        return name -> {
            if (egress) {
                Matcher m = GEOTOPIC_ALT_V4.matcher(name);
                if (!m.matches()) {
                    return null;
                }
                return "Optional_" + GEOTOPIC_ALT_WORDS_V4_TO_V3.get(m.group(1)) + m.group(2);
            } else {
                Matcher m = GEOTOPIC_ALT_V3.matcher(name);
                if (!m.matches()) {
                    return null;
                }
                return "geotopic:alt-" + m.group(1).toLowerCase(Locale.ROOT) + m.group(2);
            }
        };
    }

    /** {@code tk:digest:<jca-alg>[:enc]} &harr; {@code X-TIKA:digest:<enum-alg>[:enc]} (encoding kept). */
    private static UnaryOperator<String> digestRule(Direction direction) {
        boolean egress = direction == Direction.V4_TO_V3;
        String fromPrefix = egress ? V4_DIGEST : V3_DIGEST;
        String toPrefix = egress ? V3_DIGEST : V4_DIGEST;
        Map<String, String> alg = new HashMap<>();
        DIGEST_ALG_V4_TO_V3.forEach((v4, v3) -> alg.put(egress ? v4 : v3, egress ? v3 : v4));
        return name -> {
            if (!name.startsWith(fromPrefix)) {
                return null;
            }
            String rest = name.substring(fromPrefix.length());   // <alg> or <alg>:<enc>
            int c = rest.indexOf(':');
            String a = c < 0 ? rest : rest.substring(0, c);
            String enc = c < 0 ? "" : rest.substring(c);
            return toPrefix + alg.getOrDefault(a, a) + enc;
        };
    }
}
